title: Yili Zhao
description: My Personal Blog
author: Yili Zhao
logo: /static/img/avatar.png
github: https://github.com/panovr
about: Freelance developer

baseurl: ""
url: "https://panovr.github.io"

allowsearch: true

disqus_shortname: panovr
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
